'use strict';
module Application {
    export var SCREEN_AFSCHRIFT_LIJST = "SCREEN_AFSCHRIFT_LIJST";
    export var SCREEN_AFSCHRIFT_EDIT = "SCREEN_AFSCHRIFT_EDIT";
    export var SCREEN_AFSCHRIFT_RUBRICEER_REGELS = "SCREEN_AFSCHRIFT_RUBRICEER_REGELS";
    export var SCREEN_AFSCHRIFT_CHECK_AND_FIX_REGELS = "SCREEN_AFSCHRIFT_CHECK_AND_FIX_REGELS";
}
