'use strict';
module Application {
    export var SCREEN_FACTUUR_LIJST = "SCREEN_FACTUUR_LIJST";
    export var SCREEN_FACTUUR_EDIT = "SCREEN_FACTUUR_EDIT";
    export var SCREEN_FACTUUR_REGEL = "SCREEN_FACTUUR_REGEL";
    export var SCREEN_FACTUUR_CONTACT = "SCREEN_FACTUUR_CONTACT";
    export var SCREEN_FACTUUR_EDIT_DETAIL = "SCREEN_FACTUUR_EDIT_DETAIL";
    export var SCREEN_FACTUUR_EDIT_CONTACT = "SCREEN_FACTUUR_EDIT_CONTACT";
}
