package com.vdzon.administratie.rubriceren.model

enum class RubriceerAction {
    NONE, CREATE_REKENING, CONNECT_EXISTING_FACTUUR, CONNECT_EXISTING_REKENING, PRIVE, BETALING_ZONDER_FACTUUR, INKOMSTEN_ZONDER_FACTUUR
}
