'use strict';
module Application {
    export var SCREEN_GEBRUIKER_LIJST = "SCREEN_GEBRUIKER_LIJST";
    export var SCREEN_GEBRUIKER_EDIT = "SCREEN_GEBRUIKER_EDIT";
    export var SCREEN_GEBRUIKER_SET_PASSWD = "SCREEN_GEBRUIKER_SET_PASSWD";
}
