'use strict';
module Application {
    export var SCREEN_BESTELLING_LIJST = "SCREEN_BESTELLING_LIJST";
    export var SCREEN_BESTELLING_EDIT = "SCREEN_BESTELLING_EDIT";
    export var SCREEN_BESTELLING_REGEL = "SCREEN_BESTELLING_REGEL";
    export var SCREEN_BESTELLING_CONTACT = "SCREEN_BESTELLING_CONTACT";
    export var SCREEN_BESTELLING_EDIT_DETAIL = "SCREEN_BESTELLING_EDIT_DETAIL";
    export var SCREEN_BESTELLING_EDIT_CONTACT = "SCREEN_BESTELLING_EDIT_CONTACT";
}
